services:
  - type: web
    name: hackify-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn hackify_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: hackify-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: hackify-db
    databaseName: hackify
    user: hackify
    plan: free